"""'change db fields'

Revision ID: 8fbca39e64ed
Revises: 232d3732ab43
Create Date: 2025-10-24 13:18:10.709588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbca39e64ed'
down_revision: Union[str, None] = '232d3732ab43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rules_user_notification_ids_key'), 'rules', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('rules_user_notification_ids_key'), 'rules', ['user_notification_ids'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
