"""'change db fields'

Revision ID: 1b8da0c2b876
Revises: 9bab49747b07
Create Date: 2025-10-24 09:28:54.911063

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b8da0c2b876"
down_revision: Union[str, None] = "9bab49747b07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "notifications", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "notifications",
        "notification_type_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "notifications", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "notifications_types",
        "name",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "notifications_types",
        "description",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "sources_types", "name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "sources_types",
        "description",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column("triggers", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("triggers", "source_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "triggers", "trigger_type_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "triggers",
        "config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("triggers", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "triggers_types", "name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "triggers_types",
        "description",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "triggers_types",
        "description",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "triggers_types", "name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("triggers", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "triggers",
        "config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "triggers", "trigger_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("triggers", "source_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("triggers", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "sources_types",
        "description",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "sources_types", "name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "notifications_types",
        "description",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "notifications_types",
        "name",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "notifications", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "notifications",
        "notification_type_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "notifications", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
