"""'change db fields'

Revision ID: e00d90643836
Revises: 29f3afd64d50
Create Date: 2025-10-24 12:41:41.161789

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e00d90643836"
down_revision: Union[str, None] = "29f3afd64d50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rules", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("rules", "source_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("rules", "trigger_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("rules", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_constraint(op.f("rules_user_notification_ids_key"), "rules", type_="unique")
    op.create_unique_constraint(
        "uq_rules_user_source_trigger", "rules", ["user_id", "source_id", "trigger_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_rules_user_source_trigger", "rules", type_="unique")
    op.create_unique_constraint(
        op.f("rules_user_notification_ids_key"),
        "rules",
        ["user_notification_ids"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column("rules", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("rules", "trigger_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("rules", "source_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("rules", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
