"""'change db fields'

Revision ID: 9b05d4bde71e
Revises: 1b8da0c2b876
Create Date: 2025-10-24 09:41:38.149204

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b05d4bde71e"
down_revision: Union[str, None] = "1b8da0c2b876"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rules",
        sa.Column("user_notification_ids", sa.ARRAY(sa.Integer()), nullable=True),
    )
    op.drop_column("rules", "user_notification_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rules",
        sa.Column(
            "user_notification_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("rules", "user_notification_ids")
    # ### end Alembic commands ###
