"""'change db fields'

Revision ID: 29f3afd64d50
Revises: 9b05d4bde71e
Create Date: 2025-10-24 12:32:36.041518

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29f3afd64d50"
down_revision: Union[str, None] = "9b05d4bde71e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "rules", ["user_notification_ids"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rules", type_="unique")
    # ### end Alembic commands ###
